new poison feature added
andrewoid/Snake-1 pull request #3
Opened 2018-05-14 06:29 UTC by scohen40

2018-05-14 13:20 UTC, andrewoid requested changes

2018-05-14 13:20 UTC, andrewoid commented on Snake/Snake.java
> +		if(size > 0) {
If your size is zero you should probably lose the game. This also means that the size variable will be out of sync with the length of the List.

2018-05-14 13:20 UTC, andrewoid commented on Snake/GameBoard.java
> +class GameBoard extends JFrame {
According to the pull request it appears you changed every line of GameBoard. Please revert your changes and only modify the lines that you need to change.

2018-05-14 13:20 UTC, andrewoid commented on Snake/Snake.java
> +    void cutDown (int x) {
Is this method ever used?

2018-05-15 20:08 UTC, scohen40 commented
How do you revert the changes?

On Mon, May 14, 2018 at 9:21 AM, Andrew Schwimmer <notifications@github.com>
wrote:

> *@andrewoid* requested changes on this pull request.
> ------------------------------
>
> In Snake/Snake.java
> <https://github.com/andrewoid/Snake-1/pull/3#discussion_r187948878>:
>
> > @@ -145,6 +145,24 @@ void grow () {
>      public void grow (int x) {
>          size += x;
>      }
> +
> +    /**
> +     * Cuts the snake by one tile.
> +     */
> +    void cutDown () {
> +		size--;
> +		if(size > 0) {
>
> If your size is zero you should probably lose the game. This also means
> that the size variable will be out of sync with the length of the List.
> ------------------------------
>
> In Snake/GameBoard.java
> <https://github.com/andrewoid/Snake-1/pull/3#discussion_r187949333>:
>
> > -                    sb.append("S");
> -                } else if (food.equals(sq)) {
> -                    sb.append("F");
> -                } else {
> -                    sb.append("-");
> -                }
> -
> -                sb.append(" ");
> -
> -            }
> -            sb.append("\n");
> -        }
> -
> -        return new String(sb);
> -    }
> +class GameBoard extends JFrame {
>
> According to the pull request it appears you changed every line of
> GameBoard. Please revert your changes and only modify the lines that you
> need to change.
> ------------------------------
>
> In Snake/Snake.java
> <https://github.com/andrewoid/Snake-1/pull/3#discussion_r187949567>:
>
> > +
> +    /**
> +     * Cuts the snake by one tile.
> +     */
> +    void cutDown () {
> +		size--;
> +		if(size > 0) {
> +			snakeList.remove(snakeList.size() - 1);
> +		}
> +    }
> +
> +    /**
> +     * Cuts the snake a specified number of tiles.
> +     * @param x		the number of tiles to cut the snake by
> +     */
> +    void cutDown (int x) {
>
> Is this method ever used?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/andrewoid/Snake-1/pull/3#pullrequestreview-119828477>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ASeqRqccdxaD_aQmC0N5wVwv-OCLApHwks5tyYTRgaJpZM4T9ObT>
> .
>

2018-05-15 20:27 UTC, closed without merging